### ISSUE TITLE
gh-pages branch is expanding in size

### ISSUE THREAD

**Issue by navidcy** [fredrikekre/Literate.jl#109]
I'm wondering what's the best practice for Literating examples (with figures and animations) so that `gh-pages` branch don't get out of hand. See, e.g. https://github.com/FourierFlows/GeophysicalFlows.jl/issues/76.

For example, in the `generated` folder (https://github.com/FourierFlows/GeophysicalFlows.jl/tree/gh-pages/dev/generated) I see both `.mp4` files and `.ipynb` that probably include the movie in them (judging from their file size). Should I be deleting either before calling `deploydocs()`?

(I'm not sure if this belongs better in [Documenter.jl])https://github.com/JuliaDocs/Documenter.jl).)

**Comment by fredrikekre** [comment]
Yes, you can clean up files if you don't want to deploy them. You can also just purge the gh-pages branch since it is completely disconnected from the master branch, so you can just squash it down to 1 commit.

See also https://github.com/JuliaDocs/Documenter.jl/issues/1306 which is tangentially related.
