### ISSUE TITLE
Set up binder for deployed/generated notebook outputs

### ISSUE THREAD

**Issue by diegozea** [fredrikekre/Literate.jl#46]
It will be great to have add a way to include a `REQUIRE` file in the `gh-pages` branch to use [binder](https://mybinder.org/) to interact with the generated outputs: https://github.com/binder-examples/demo-julia
Also, to have something similar to `@__NBVIEWER_ROOT_URL__` to add the launch binder icon.

**Comment by diegozea** [comment]
I don't have to much experience either. I think that binder needs for Julia a `REQUIRE` file in the repo directory that it's used to set up a docker image to run the IJulia notebook.
In this case, we need a way to add a `REQUIRE` file in the `gh-pages` branch during the deployment process. The  `REQUIRE` file should have the list of Julia packages and the Julia version required to run the Literate-generated notebooks.
Then, as nbviewer, binder generates a link to the notebook, e.g.:
https://mybinder.org/v2/gh/binder-examples/demo-julia/master?filepath=demo.ipynb

**Comment by briochemc** [comment]
I'm not sure why but my binder links do not work properly (e.g., [here](https://briochemc.github.io/AIBECS.jl/stable/howtos/2_plot/)). Clicking on the link actually opens the notebook in binder but it cannot find the Julia kernel, as illustrated in this screenshot:

![Screen Shot 2019-12-04 at 8 58 51 AM](https://user-images.githubusercontent.com/4486578/70095174-3340e900-1678-11ea-973d-5d53b849f5cd.png)

Maybe I'm completely wrong about this but I think that binder works here (in the Literate binder example) because you manually added the `docs/Project.toml` and `docs/Manifest.toml` files from the `master` branch to the `gh-pages` branch in commit https://github.com/fredrikekre/Literate.jl/commit/b5a0fc2809ca7a914a3c48934884b3e50508b602. 

If I am correct, these `.toml` files play the role of the REQUIRE mentioned in this issue, so it would be nice to automatically (or at least optionally) copy them from, e.g., the `master` branch to the `gh-pages` branch. (Also maybe just the Project.toml file is required?)

**Comment by fredrikekre** [comment]
Yea, you need to add them there.
